<a href="https://colab.research.google.com/github/khikmat64168-cyber/Ai-fundatin/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:

print(pd.__version__)

2.2.3

In [5]:

mydataset = {
    'cars':['BMW', "Volvo", 'Ford', 'Tesla', 'Ferrari', 'Ford', "Mers"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6     Mers       3

In [6]:
df.head(5) # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [7]:

df.tail(-1) # default 5 rows

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6     Mers       3

In [8]:

df.shape

(7, 2)

In [9]:

df.columns

Index(['cars', 'counts'], dtype='object')

In [10]:

df.dtypes

cars      object
counts     int64
dtype: object

In [11]:

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6     Mers       3

In [12]:
df.describe() # numerical columns only

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [13]:
df.iloc[0]

cars      BMW
counts      3
Name: 0, dtype: object

In [14]:
df.loc[2:5, 'cars']

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [15]:
df[df['counts'] > 3]

    cars  counts
1  Volvo       7
3  Tesla       8
5   Ford       9

In [16]:

# df.mean(numeric_only=True)
df['counts'].mean()

np.float64(4.714285714285714)

In [17]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordMers
counts                                  33
dtype: object

In [18]:
df.min()

cars      BMW
counts      1
dtype: object

In [19]:
df.max()

cars      Volvo
counts        9
dtype: object

In [20]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [21]:
df.count()

cars      7
counts    7
dtype: int64

In [22]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [25]:
import pandas as pd

In [34]:
data_with_missing = {
    'cars': ['BMW', 'Volvo', None, 'Tesla', 'ferrari', None, 'Ford'],
    'counts': [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

display(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  ferrari     1.0
5     None     9.0
6     Ford     NaN

In [27]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [28]:
df_missing.dropna(subset=['cars'])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  ferrari     1.0
6     Ford     NaN

In [29]:
df_missing.fillna({'cars': 'unknown', "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [35]:
!unzip -o /content/archive.zip -d /content/extracted_data
!ls -la /content/extracted_data

Archive:  /content/archive.zip
  inflating: /content/extracted_data/Titanic-Dataset.csv
total 68
drwxr-xr-x 2 root root  4096 Oct 20 08:43 .
drwxr-xr-x 1 root root  4096 Oct 20 08:42 ..
-rw-r--r-- 1 root root 61194 Dec 24  2021 Titanic-Dataset.csv

In [36]:
# df = pd.read_csv("Titanic-Dataset.csv")

df = pd.read_excel("test.xlsx")

df.tail()

# df = pd.read_excel("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [38]:
df.to_excel("test.xlsx")

In [39]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [40]:

cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'ferrari', None, 'Ford']